Repository mr-Hacker-Boy/Hello-world, pull requests merged in 2022-10, with the labels that each got.

#1 Update readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#3 Create helloworld_sd.c
  C/helloworld_sd.c
Labels: hacktoberfest-accepted

#10 Create hello-world.cpp
  C++/hello-world.cpp
Labels: hacktoberfest

#9 Create helloworld_sd.java
  Java/helloworld_sd.java
Labels: hacktoberfest-accepted
